### ISSUE TITLE
Crash when getting into cedar raft with sail on singleplayer.

### ISSUE THREAD

**Issue by Microgorath** [Moby4585/Joy-of-Sailing#5]
Had a crash instantly after right clicking to get into a cedar raft with sail on singleplayer world. Unlike #4, had no issue placing the boat, only crashed when trying to get into the boat. Upon trying to reload that world, it now instantly crashes upon loading in (it probably saved the instant I got on the boat, which now causes it to instantly crash...)

First crash report from getting on boat:
=========================
Running on 64 bit Windows 10.0.22621.0 with 65277 MB RAM
Game Version: v1.19.0-rc.5 (Unstable)
1/6/2024 6:08:11 AM: Critical error occurred in the following mod: sailboat@1.2.4
Loaded Mods: hqzlights@1.1.1, caninae@1.0.7, immersivecorpsedrop@1.0.2, justmoreruins@0.9.8, meteoricexpansion@1.2.4, millwright@1.1.3, qptech@1.14.1, translocatorengineeringredux@1.4.9, game@1.19.0-rc.5, wildcrafttrees@1.2.4, alchemy@1.6.22, carryon@1.7.0-pre.3, sailboat@1.2.4, medievalexpansion@3.12.0, rivers@1.1.2, creative@1.19.0-rc.5, survival@1.19.0-rc.5, metalrecovery@0.1.19-pre.1, bullseye@2.5.1, simplewinddirection@1.0.2
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.AnimManager'.
   at sailboat.EntitySailboat.SeatsToMotion(Single dt)
   at sailboat.EntitySailboat.updateBoatAngleAndMotion(Single dt) in D:\Documents\Developpement\_Vintage Story\vsmods_vscode\josailing\josailing\src\entity\EntitySailboat.cs:line 347
   at sailboat.EntitySailboat.OnRenderFrame(Single dt, EnumRenderStage stage) in D:\Documents\Developpement\_Vintage Story\vsmods_vscode\josailing\josailing\src\entity\EntitySailboat.cs:line 149
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Crash report after relaunching game and reloading world:
=====================================
Running on 64 bit Windows 10.0.22621.0 with 65277 MB RAM
Game Version: v1.19.0-rc.5 (Unstable)
1/6/2024 6:14:48 AM: Critical error occurred in the following mod: sailboat@1.2.4
Loaded Mods: hqzlights@1.1.1, caninae@1.0.7, immersivecorpsedrop@1.0.2, justmoreruins@0.9.8, meteoricexpansion@1.2.4, millwright@1.1.3, qptech@1.14.1, translocatorengineeringredux@1.4.9, game@1.19.0-rc.5, wildcrafttrees@1.2.4, alchemy@1.6.22, carryon@1.7.0-pre.3, sailboat@1.2.4, medievalexpansion@3.12.0, rivers@1.1.2, creative@1.19.0-rc.5, survival@1.19.0-rc.5, metalrecovery@0.1.19-pre.1, bullseye@2.5.1, simplewinddirection@1.0.2
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.AnimManager'.
   at sailboat.EntitySailboat.SeatsToMotion(Single dt)
   at sailboat.EntitySailboat.updateBoatAngleAndMotion(Single dt) in D:\Documents\Developpement\_Vintage Story\vsmods_vscode\josailing\josailing\src\entity\EntitySailboat.cs:line 335
   at sailboat.EntitySailboat.OnRenderFrame(Single dt, EnumRenderStage stage) in D:\Documents\Developpement\_Vintage Story\vsmods_vscode\josailing\josailing\src\entity\EntitySailboat.cs:line 154
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 799
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 851
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 723
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
-------------------------------------------------------
{ TimeGenerated = 1/5/2024 3:56:57 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0x5604
Faulting application start time: 0x0x1da3fb4e0073a8a
Faulting application path: C:\Games\Vintagestory\Vintagestory.exe
Faulting module path: C:\Games\Vintagestory\Lib\openal32.dll
Report Id: 4f6862bc-ee42-4499-90f1-ea856334b41a
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by kitsushadow** [comment]
+1 same issue
