### ISSUE TITLE
Multiplayer crash when picking up the boat

### ISSUE THREAD

**Issue by kitsushadow** [Moby4585/Joy-of-Sailing#6]
Running on 64 bit Windows 10.0.19045.0 with 32713 MB RAM
Game Version: v1.19.1 (Stable)
1/20/2024 1:40:05 PM: Critical error occurred in the following mod: sailboat@1.2.6
Loaded Mods: arrowheadsrecovery_fork@1.0.0, autosifter@1.1.0, bettersticks@1.0.0, cellardoor@1.4.0, claycasting@1.1.2, Clothez@1.0.0, driftersbelongunderground@1.0.1, flourbags@1.0.1, caninae@1.0.8, giantgouramis@1.0.2, harptechfix@1.2.4, immersivecorpsedrop@1.0.2, lessfoliage@1.0.0, millwright@1.1.3, MoveLikeKaji@0.0.5, peacockbasses@1.1.2, primitivesurvival@3.4.5, propickfix@1.0.0, sca@1.0.1, spyglass@0.5.0, Swordz@1.1.4, temporal_gears_stack@1.0.0, truesunfishes@1.1.2, game@1.19.1, ancienttools@1.5.12, BedRespawning@1.0.1, betterfirepit@1.1.3, commonlib@2.3.2, electricity@0.0.10, fieldsofsalt@1.2.0, fromgoldencombs@1.4.25, herbarium@1.0.4, sailboat@1.2.6, minerz@0.0.3, moreanimals@1.3.1, mcrate@1.2.0, petai@2.2.1, prospecttogether@1.3.0-rc.3, scarecrow@1.4.0, simplestep@1.0.9, spearsplus@1.0.0, creative@1.19.1, vsimgui@0.2.2, survival@1.19.1, metalrecovery@0.1.19-pre.1, bugnetcompatibility@1.0.1, configlib@0.3.2, feverstonehorses@1.6.0, linearpower@0.2.1, morerope@2.0.1, playercorpse@1.9.0, stonequarry@3.2.1, statushudcont@2.1.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at sailboat.EntitySailboat.OnInteract(EntityAgent byEntity, ItemSlot itemslot, Vec3d hitPosition, EnumInteractMode mode) in D:\Documents\Developpement\_Vintage Story\vsmods_vscode\josailing\josailing\src\entity\EntitySailboat.cs:line 507
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 386
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by kitsushadow** [comment]
This happens when pressing CTRL + Right Click

**Comment by kitsushadow** [comment]
While playing around this bug i find that it could work well as a feature. Not being able to pick it up seems legitimate for a boat. At best it should take a backpack slot. IDK, sharing my experiences with it.

**Comment by WickedSchnitzel** [comment]
we are getting the same crash. modded multiplayer server. v1.2.6 on 1.19.1
